<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="CrudAsp.aspx.cs" Inherits="CrudAppAspnet.CrudAsp" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style>
     

        #GridView1{
            margin:auto;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
        </div>
    &nbsp;&nbsp;
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" DataKeyNames="Id" DataSourceID="SqlDataSource1" Height="261px" Width="1039px" ShowFooter="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged1">
          
            <Columns>
                <asp:TemplateField HeaderText="Id" InsertVisible="False" SortExpression="Id">
                    <EditItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Eval("Id") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                    </ItemTemplate>
                                     
                    







                    <FooterTemplate>
                         <asp:LinkButton OnClick="Unnamed_Click" ValidationGroup="Insert" runat="server">Insert</asp:LinkButton>
                    </FooterTemplate>
                </asp:TemplateField>








                <asp:TemplateField HeaderText="ClientName" SortExpression="ClientName">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("ClientName") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("ClientName") %>'></asp:Label>
                    </ItemTemplate>
                       
                    <FooterTemplate>
                        <asp:TextBox ID="TextBox6" runat="server"></asp:TextBox>
                        <asp:RequiredFieldValidator ValidationGroup="Insert" SetFocusOnError="true" ID="RequiredFieldValidator1" ControlToValidate="TextBox6" Text="*"  ForeColor="Red" runat="server" ErrorMessage="Enter Client Name"></asp:RequiredFieldValidator>


                    </FooterTemplate>

                </asp:TemplateField>



                <asp:TemplateField HeaderText="ProductNumber" SortExpression="ProductNumber">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("ProductNumber") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("ProductNumber") %>'></asp:Label>
                    </ItemTemplate>
                       
                    <FooterTemplate>
                        <asp:TextBox ID="TextBox7" runat="server" TextMode="Number"></asp:TextBox>
                    <asp:RequiredFieldValidator SetFocusOnError="true" ValidationGroup="Insert" ID="RequiredFieldValidator2" ControlToValidate="TextBox7" Text="*"  ForeColor="Red" runat="server" ErrorMessage="Enter Product Number"></asp:RequiredFieldValidator>

                    </FooterTemplate>
                 
                </asp:TemplateField>


                <asp:TemplateField HeaderText="ProductName" SortExpression="ProductName">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("ProductName") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("ProductName") %>'></asp:Label>
                    </ItemTemplate>

                       
                    <FooterTemplate>
                        <asp:TextBox ID="TextBox8" runat="server"></asp:TextBox>
                           <asp:RequiredFieldValidator SetFocusOnError="true" ValidationGroup="Insert" ID="RequiredFieldValidator3" ControlToValidate="TextBox8" Text="*"  ForeColor="Red" runat="server" ErrorMessage="Enter Product Name"></asp:RequiredFieldValidator>

                    </FooterTemplate>
                </asp:TemplateField>


                <asp:TemplateField HeaderText="Quantity" SortExpression="Quantity">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("Quantity") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label5" runat="server" Text='<%# Bind("Quantity") %>'></asp:Label>
                    </ItemTemplate>
                       
                    <FooterTemplate>
                        <asp:TextBox ID="TextBox9" runat="server" TextMode="Number"></asp:TextBox>
                         <asp:RequiredFieldValidator SetFocusOnError="true"  ValidationGroup="Insert" ID="RequiredFieldValidator4" ControlToValidate="TextBox9" Text="*"  ForeColor="Red" runat="server" Display="Dynamic" ErrorMessage="Enter Quantity "></asp:RequiredFieldValidator>
<%--                        <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ControlToValidate="TextBox9" ForeColor="Red" SetFocusOnError="true" Text="*" Display="Dynamic" TextMode="Number" ErrorMessage="Enter only numbers"></asp:RegularExpressionValidator>--%>
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="DateAndTime" SortExpression="DateAndTime">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox5" runat="server" Text='<%# Bind("DateAndTime") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label6" runat="server" Text='<%# Bind("DateAndTime") %>'></asp:Label>
                    </ItemTemplate>
                       
                    <FooterTemplate>
                        <asp:TextBox ID="TextBox10" runat="server" TextMode="DateTimeLocal"></asp:TextBox>
                        <asp:RequiredFieldValidator SetFocusOnError="true"  ValidationGroup="Insert" ID="RequiredFieldValidator5" ControlToValidate="TextBox10" Text="*"  ForeColor="Red" runat="server" ErrorMessage="Enter Date and Time"></asp:RequiredFieldValidator>

                    </FooterTemplate>
                </asp:TemplateField>
            </Columns>


            <FooterStyle BackColor="White" ForeColor="#000066" />
            <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
            <RowStyle ForeColor="#000066" />
            <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#007DBB" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#00547E" />
        </asp:GridView>





        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [Emp] WHERE [Id] = @Id" InsertCommand="INSERT INTO [Emp] ([ClientName], [ProductNumber], [ProductName], [Quantity], [DateAndTime]) VALUES (@ClientName, @ProductNumber, @ProductName, @Quantity, @DateAndTime)" SelectCommand="SELECT * FROM [Emp]" UpdateCommand="UPDATE [Emp] SET [ClientName] = @ClientName, [ProductNumber] = @ProductNumber, [ProductName] = @ProductName, [Quantity] = @Quantity, [DateAndTime] = @DateAndTime WHERE [Id] = @Id">
            <DeleteParameters>
                <asp:Parameter Name="Id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="ClientName" Type="String" />
                <asp:Parameter Name="ProductNumber" Type="Int32" />
                <asp:Parameter Name="ProductName" Type="String" />
                <asp:Parameter Name="Quantity" Type="Int32" />
                <asp:Parameter Name="DateAndTime" Type="DateTime" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="ClientName" Type="String" />
                <asp:Parameter Name="ProductNumber" Type="Int32" />
                <asp:Parameter Name="ProductName" Type="String" />
                <asp:Parameter Name="Quantity" Type="Int32" />
                <asp:Parameter Name="DateAndTime" Type="DateTime" />
                <asp:Parameter Name="Id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <asp:ValidationSummary ID="ValidationSummary1" ValidationGroup="Insert" runat="server" ForeColor="Red" BorderStyle="Solid" />
    </form>
</body>
</html>
